using System.ComponentModel.DataAnnotations;
using JsonBridgeEF.Seeding.TargetModel.Models;

namespace JsonBridgeEF.ZZZ
{
    /// <summary>
    /// Registers the persistent association between a business key extracted from the JSON and the target ID
    /// generated by the database.
    /// </summary>
    internal class EntityKeyMapping
    {
        /// <summary>
        /// Primary key for the key mapping record.
        /// </summary>
        [Key]
        public int Id { get; set; }

        /// <summary>
        /// The business key extracted from the JSON (for example, the value of "utente.id" or a composite key).
        /// </summary>
        [Required]
        public string JsonKey { get; set; } = string.Empty;

        /// <summary>
        /// Foreign key to the TargetPropertyDef that indicates the target model.
        /// </summary>
        [Required]
        public int TargetPropertyDefId { get; set; }

        /// <summary>
        /// The key generated by the target database for the associated entity.
        /// This field can be null if the entity has not yet been saved.
        /// </summary>
        public int? TargetId { get; set; }

        /// <summary>
        /// Timestamp of when this mapping record was created.
        /// </summary>
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// Timestamp of the last update to this mapping record.
        /// </summary>
        public DateTime? UpdatedAt { get; set; }

        // Navigation property (facoltativa per EF Core)
        /// <summary>
        /// Gets or sets the target entity definition associated with this mapping.
        /// </summary>
        public virtual TargetPropertyDef TargetPropertyDef { get; set; } = null!;
    }
}